### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by endolith** [1313e/CMasher#17]
Any reason not to list it as `pip install git+https://github.com/1313e/CMasher.git` ?

**Comment by 1313e** [comment]
@endolith Mostly, because that results in basically the same thing as `pip install cmasher`.
At least when cloning it yourself, you actually have access to the repo.

The other reason is that the CMasher repo is rather large due to the large number of files that are in there.
One should not clone the repo unless they explicitly want access to all those files.
