### ISSUE TITLE
Possible contribution: some sequential, some ~diverging

### ISSUE THREAD

**Issue by adrn** [1313e/CMasher#37]
I have a set of colormaps that I have found useful in various contexts, and I was just [going through the process of packaging them](https://cmastro.readthedocs.io/en/latest/) when @dfielding14 pointed me to this repo :). So, checking in here to see if you would be open to contributions.

![colormaps](https://cmastro.readthedocs.io/en/latest/_images/index-1.png)

**Describe the colormap type**

The first three are sequential and come from here: http://inversed.ru/Blog_2.htm

The two `emph` and `unph` are made from stitching together pieces of Hesperia and Laguna and satisfy some constraints that I wanted, but couldn't find in any other colormaps:
- Close to cyclic, but with unique colors on either end
- Options to either emphasize the central values / or de-emphasize central values
- "Cool" colors on one side, "warm" colors on the other side (so that positive/negative are unique)
- Print to black and white in a way that preserves lightness
- Close to perceptually uniform in either direction

These are different from many of the existing diverging and cyclic maps because they don't go to fully to white or black, so colors are meant to be unique anywhere. (although "guppy" and "pride" look close?)

**Describe any extra properties**

In B&W:
![image](https://user-images.githubusercontent.com/583379/116288823-e58eba00-a75f-11eb-8ace-902ea7b508d2.png)

Lightness curves:
![image](https://user-images.githubusercontent.com/583379/116288862-ee7f8b80-a75f-11eb-8fa6-511b25817aba.png)

If interested, happy to open a PR with the relevant colormap data...

**Comment by 1313e** [comment]
Hi @adrn,
good to see others making good colormaps out there.

Regarding adding colormaps to CMasher: I am incredibly picky when it comes to this, as also mentioned in [the online docs](https://cmasher.readthedocs.io/user/FAQ.html#can-i-add-my-own-colormaps).
For example, they must be fully perceptually uniform sequential and unique when compared to the colormaps that are already in CMasher.
Looking at the lightness curves you posted, I can see that these colormaps are not fully perceptually uniform sequential.
I get the feeling they were made using the Catmul Clark curves in `viscm`, which sadly do not produce proper colormaps (use Bezier curves instead).

Regarding uniqueness, this is a bit of a general issue I am starting to have in CMasher: Making colormaps distinct from each other.
In your case, `laguna` is very close to `ocean` but with a black end (which I specifically did not want when I made `ocean`); `emph` and `unph` come relatively close to `guppy` and `pride` as you mentioned (although I do think they are distinct enough to be included in CMasher if we come to an agreement); `hesperia` is incredibly close to `magma` in MPL; and `lacerta` is close to a mixture of `jungle` and `swamp`.
Note that I am not saying that these are bad or unwanted colormaps, not at all.
I really like the colormaps you are presenting here, but the issue is that they are rather similar to colormaps that are already in CMasher.
Adding them to CMasher would become very confusing for users, as they no longer can really tell the difference between which colormap is which.

What I am trying to say here is that only `emph` would really be an addition to CMasher (as `unph` is absolutely not perceptually uniform sequential), as the other ones are too similar to already existing colormaps (especially `hesperia`, as I am trying to stay away from creating colormaps that are close to those in MPL), despite looking very good.
However, of course, as you have already done, I would highly encourage you to create your own colormap package to provide them in.
This is especially useful if you ever feel the urge to create a new colormap; you just add them to your already existing package, instead of having to open a PR here again. :)

So, if you want, we could add `emph` to CMasher, but I personally think it is much better if you create and maintain your own package for this (as you have already done).
