### ISSUE TITLE
2D Colormaps

### ISSUE THREAD

**Issue by dfielding14** [1313e/CMasher#46]
Hello,

I am long time admirer and user of your great colormaps! 

Lately I have been playing around a little bit with making 2D colormaps from your original 1D colormaps. To do this I shift the overall lightness / darkness of the whole color map. However, my current implementation is very rudimentary, all I do is linearly interpolate the rgb values up or down based on the second variable I am plotting against. This linear interpolation does not preserve perceptual uniformity, so I was wondering if you have any thoughts on how I could do this more rigorously.  You can see an example in the following image where black to white encodes Log T, and color encodes f_sat. 
<img width="280" alt="Screen Shot 2022-11-02 at 1 21 31 PM" src="https://user-images.githubusercontent.com/4324211/199558231-23cf3ef8-747c-43bb-8ff7-cade77d4d677.png">

My initial attempt to do this was somewhat more perceptually uniform, but much less vivid and harder to discern the intermediate color values.
<img width="282" alt="Screen Shot 2022-11-02 at 1 23 15 PM" src="https://user-images.githubusercontent.com/4324211/199558546-32b871d0-bedb-4c3d-aa0d-df6e906b997d.png">

What do you think?

**Comment by 1313e** [comment]
I have tried many times to make colormaps like that before, but yeah, you cannot have vivid colors while also maintaining perceptual uniformity across the entire colormap.
Often you just end up with something like your second example.
The big reason for that is because requiring that lightness and saturation change linearly, forces you to pick a very specific hue, leaving little room for color changes as well.

**Comment by neutrinoceros** [comment]
https://github.com/matplotlib/matplotlib/issues/14168
